CREATE SCHEMA LK;

CREATE TABLE INFORMACOES(
    CODIGO SMALLINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    IDADE INT NOT NULL,
    SOMADTNASC INT NOT NULL
)AUTO_INCREMENT = 1;

ALTER TABLE INFORMACOES ADD CONSTRAINT PK_INFORMACOES PRIMARY KEY (CODIGO);